# This is a basic workflow to help you get started with Actions

name: Build and deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

  schedule:
    - cron: '0 5 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16','18','20']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push prod
        id: docker_build_prod
        uses: docker/build-push-action@v3
        with:
          push: true
          target: production
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node-base-image:${{ matrix.node-version }}
          build-args: NODE_VERSION=${{ matrix.node-version }}

      - name: Image digest
        run: echo ${{ steps.docker_build_prod.outputs.digest }}

  latest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push 18 to latest
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/node-base-image:18
          dst: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/node-base-image:latest
